# ------------------------------------------------------------------------ #
# Copyright 2026 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# SPDX-License-Identifier: MIT-0
# ------------------------------------------------------------------------ #
from __future__ import annotations

from typing import TYPE_CHECKING

from shared.base_callbacks import BaseAgentCallbacks
from strands.hooks.events import (
    AfterToolCallEvent,
    BeforeToolCallEvent,
)

if TYPE_CHECKING:
    from logging import Logger


class AgentCallbacks(BaseAgentCallbacks):
    """Class to handle callbacks for agent operations.

    This class extends BaseAgentCallbacks with trajectory enrichment features
    for evaluation purposes. It stores tool arguments and results keyed by tool_call_id
    to enable post-processing of agent trajectories.

    Attributes:
        _metadata (dict): Dictionary storing metadata generated by tools, e.g. Knowledge base references.
        _logger (Logger): Logger instance for recording agent operations and tool usage.
        _tool_executions (dict): Dictionary mapping tool_call_id to tool execution data.
    """

    def __init__(self, logger: Logger, session_id: str, user_id: str) -> None:
        super().__init__(logger, session_id, user_id)
        self._tool_executions: dict[str, dict] = {}

    def reset_metadata(self) -> None:
        """Reset metadata, tool invocation counter, and tool executions."""
        super().reset_metadata()
        self._tool_executions = {}

    @property
    def tool_executions(self) -> dict[str, dict]:
        """Get captured tool execution data keyed by tool_call_id.

        Used by app.py to enrich trajectory with tool arguments and results.
        """
        return self._tool_executions

    def log_tool_entries(self, event: BeforeToolCallEvent) -> None:
        """Logs information about tool invocation before it occurs.

        Stores tool arguments for trajectory enrichment used by evaluation features.

        Args:
            event (BeforeToolCallEvent): Event containing metadata about the tool
                that will be invoked.

        Returns:
            None
        """
        specs = event.selected_tool.tool_spec if event.selected_tool else None

        self._nb_tool_invocations += 1

        self._logger.info(
            f"Agent is going to call tool #{self._nb_tool_invocations} in this turn",
            extra={"toolSpecifications": specs, "toolParameters": event.tool_use},
        )

        # Store tool input for trajectory enrichment keyed by tool_call_id
        # This is used by app.py to post-process the trajectory with complete tool data
        tool_call_id = event.tool_use.get("toolUseId", "")
        tool_name = event.tool_use.get("name", "unknown")
        tool_input = event.tool_use.get("input", {})

        if tool_call_id:
            self._tool_executions[tool_call_id] = {
                "name": tool_name,
                "arguments": tool_input,
            }
            self._logger.debug(
                f"Stored tool input for trajectory enrichment: {tool_call_id}",
                extra={"toolName": tool_name, "toolInput": tool_input},
            )

        # Extract parameters using base class helper
        parameters = self._extract_tool_parameters(event, specs)

        # Publish tool invocation using base class helper
        tool_name = event.tool_use.get("name", "unknown")
        tool_description = specs.get("description", "") if specs else ""
        self._publish_tool_invocation(tool_name, tool_description, parameters)

    def log_tool_results(self, event: AfterToolCallEvent) -> None:
        """Logs tool results and stores them for trajectory enrichment.

        Stores tool results keyed by tool_call_id for post-processing the trajectory.
        This is required by ToolSelectionAccuracyEvaluator and ToolParameterAccuracyEvaluator.

        Args:
            event (AfterToolCallEvent): Event containing tool results.
        """
        if event.selected_tool:
            tool_name = event.selected_tool.tool_name

            self._logger.info(
                "The tool returned a response",
                extra={
                    "payload": {
                        "toolName": tool_name,
                        "results": event.result,
                    }
                },
            )

            # Store tool result for trajectory enrichment
            # Get tool_call_id from the tool_use info
            tool_call_id = (
                event.tool_use.get("toolUseId", "")
                if hasattr(event, "tool_use") and event.tool_use
                else ""
            )

            # Extract result content
            result_content = ""
            if isinstance(event.result, dict):
                content_list = event.result.get("content", [])
                if content_list and isinstance(content_list[0], dict):
                    result_content = content_list[0].get("text", str(event.result))
                else:
                    result_content = str(event.result)
            else:
                result_content = str(event.result)

            # Update the stored tool execution with result
            if tool_call_id and tool_call_id in self._tool_executions:
                self._tool_executions[tool_call_id]["result"] = result_content
                self._logger.debug(
                    f"Stored tool result for trajectory enrichment: {tool_call_id}",
                    extra={"toolName": tool_name, "resultLength": len(result_content)},
                )
