# ---------------------------------------------------------------------------- #
# Copyright 2026 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# SPDX-License-Identifier: MIT-0
#
# Streaming and configuration types shared by all the agent implementations
# ---------------------------------------------------------------------------- #
from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel


class EStreamEvent(Enum):
    """Defines the possible stream event types for streaming operations.

    Attributes:
        STREAM_COMPLETE: Event indicating that the stream has completed
        THINKING_TOKEN: Event indicating that the model is processing/thinking
        FINAL_RESPONSE_TOKEN: Event indicating a token from the final response
    """

    STREAM_COMPLETE = "STREAM_COMPLETE"
    THINKING_TOKEN = "THINKING_TOKEN"
    FINAL_RESPONSE_TOKEN = "FINAL_RESPONSE_TOKEN"


class EConversationManagerType(str, Enum):
    """Defines the possible conversation manager types for handling chat history.

    Attributes:
        NULL: No conversation management - each message is handled independently
        SLIDING_WINDOW: Maintains a sliding window of recent messages for context
        SUMMARIZING: Summarizes older messages to maintain context while managing memory
    """

    NULL = "null"
    SLIDING_WINDOW = "sliding_window"
    SUMMARIZING = "summarizing"


class StrandToken(BaseModel):
    """Represents a token generated by Strands Agents with associated event flag.

    Attributes:
        value (str): The text value of the token
        flag (EStreamEvent): The event flag associated with this token.
            See `EStreamEvent` for valid options.
    """

    value: str
    flag: EStreamEvent


class InferenceConfig(BaseModel):
    """Configuration for model inference parameters.

    Attributes:
        maxTokens (int): Maximum number of tokens to generate in the response
        temperature (float): Controls randomness in response generation. Higher values (e.g. 1.0) make output more random,
            lower values (e.g. 0.1) make it more focused and deterministic
        stopSequences (Optional[List[str]]): List of sequences that will stop text generation when encountered. Default None
    """

    maxTokens: int
    temperature: float
    stopSequences: Optional[list[str]] = None


class ModelConfiguration(BaseModel):
    """Configuration class for model inference settings.

    Attributes:
        modelId (str): Identifier for the model to be used
        parameters (InferenceConfig): Configuration parameters for model inference
    """

    modelId: str
    parameters: InferenceConfig


class Token(BaseModel):
    """Represents a token with its position in the sequence.

    Attributes:
        position (int): The position of the token in the sequence
        value (str): The text value of the token
    """

    position: int
    value: str


class ChatbotAction(Enum):
    """
    Enum class defining the possible actions that can be taken by the chatbot.

    Attributes:
        HEARTBEAT: Represents a heartbeat action to check if the chatbot is active
        RUN: Represents the main execution action of the chatbot
        ON_THINKING_TOKEN: Represents a thinking token action while the chatbot processes
        ON_NEW_LLM_TOKEN: Represents a new token received from the language model that belongs to the final answer
        FINAL_RESPONSE: Represents the final response action from the chatbot
    """

    HEARTBEAT = "heartbeat"
    RUN = "run"
    ON_THINKING_TOKEN = "on_thinking_token"
    ON_NEW_LLM_TOKEN = "on_new_llm_token"
    FINAL_RESPONSE = "final_response"
