# ---------------------------------------------------------------------------- #
# Copyright 2026 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# SPDX-License-Identifier: MIT-0
#
# Streaming and configuration types shared by all the agent implementations
# ---------------------------------------------------------------------------- #
from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, model_validator


class EStreamEvent(Enum):
    """Defines the possible stream event types for streaming operations.

    Attributes:
        STREAM_COMPLETE: Event indicating that the stream has completed
        THINKING_TOKEN: Event indicating that the model is processing/thinking
        FINAL_RESPONSE_TOKEN: Event indicating a token from the final response
    """

    STREAM_COMPLETE = "STREAM_COMPLETE"
    THINKING_TOKEN = "THINKING_TOKEN"
    FINAL_RESPONSE_TOKEN = "FINAL_RESPONSE_TOKEN"


class EConversationManagerType(str, Enum):
    """Defines the possible conversation manager types for handling chat history.

    Attributes:
        NULL: No conversation management - each message is handled independently
        SLIDING_WINDOW: Maintains a sliding window of recent messages for context
        SUMMARIZING: Summarizes older messages to maintain context while managing memory
    """

    NULL = "null"
    SLIDING_WINDOW = "sliding_window"
    SUMMARIZING = "summarizing"


class StrandToken(BaseModel):
    """Represents a token generated by Strands Agents with associated event flag.

    Attributes:
        value (str): The text value of the token
        flag (EStreamEvent): The event flag associated with this token.
            See `EStreamEvent` for valid options.
    """

    value: str
    flag: EStreamEvent


class InferenceConfig(BaseModel):
    """Configuration for model inference parameters.

    Attributes:
        maxTokens (int): Maximum number of tokens to generate in the response
        temperature (float): Controls randomness in response generation. Higher values (e.g. 1.0) make output more random,
            lower values (e.g. 0.1) make it more focused and deterministic
        stopSequences (Optional[List[str]]): List of sequences that will stop text generation when encountered. Default None
    """

    maxTokens: int
    temperature: float
    stopSequences: Optional[list[str]] = None


class ReasoningEffort(Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


# Models that require an integer reasoning budget (minimum 1024 tokens)
_INT_BUDGET_MODELS = {
    "claude-opus-4-5",
    "claude-opus-4",
    "claude-sonnet-4",
    "claude-sonnet-4-5",
    "claude-haiku-4-5",
    "claude-3-7-sonnet",
}

# Models that require a ReasoningEffort enum value
_EFFORT_BUDGET_MODELS = {
    "nova-2-lite",
    "claude-opus-4-6",
    "claude-sonnet-4-6",
}


class ModelConfiguration(BaseModel):
    """Configuration class for model inference settings.

    Attributes:
        modelId (str): Identifier for the model to be used
        parameters (InferenceConfig): Configuration parameters for model inference
        reasoningBudget (Optional[int | ReasoningEffort]): budget reserved for model reasoning,
            default to None, that means no reasoning enabled
    """

    modelId: str
    parameters: InferenceConfig
    reasoningBudget: Optional[int | ReasoningEffort] = None

    @model_validator(mode="after")
    def validate_reasoning_budget(self) -> "ModelConfiguration":
        if self.reasoningBudget is None:
            return self

        # Check effort models FIRST — their fragments are more specific
        # (e.g., "claude-opus-4-6" would otherwise match the broader "claude-opus-4")
        uses_effort = any(m in self.modelId for m in _EFFORT_BUDGET_MODELS)
        uses_int = any(m in self.modelId for m in _INT_BUDGET_MODELS)

        if uses_effort:
            if not isinstance(self.reasoningBudget, ReasoningEffort):
                raise ValueError(
                    f"reasoningBudget must be a ReasoningEffort value for model '{self.modelId}'"
                )
        elif uses_int:
            if not isinstance(self.reasoningBudget, int) or self.reasoningBudget < 1024:
                raise ValueError(
                    f"reasoningBudget must be an integer >= 1024 for model '{self.modelId}'"
                )
        else:
            raise ValueError(
                f"reasoningBudget is not supported for model '{self.modelId}'"
            )

        return self


class Token(BaseModel):
    """Represents a token with its position in the sequence.

    Attributes:
        position (int): The position of the token in the sequence
        value (str): The text value of the token
    """

    position: int
    value: str


class ChatbotAction(Enum):
    """
    Enum class defining the possible actions that can be taken by the chatbot.

    Attributes:
        HEARTBEAT: Represents a heartbeat action to check if the chatbot is active
        RUN: Represents the main execution action of the chatbot
        ON_THINKING_TOKEN: Represents a thinking token action while the chatbot processes
        ON_NEW_LLM_TOKEN: Represents a new token received from the language model that belongs to the final answer
        FINAL_RESPONSE: Represents the final response action from the chatbot
    """

    HEARTBEAT = "heartbeat"
    RUN = "run"
    ON_THINKING_TOKEN = "on_thinking_token"
    ON_NEW_LLM_TOKEN = "on_new_llm_token"
    FINAL_RESPONSE = "final_response"
