# ---------------------------------------------------------------------------- #
# Copyright 2026 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# SPDX-License-Identifier: MIT-0
# ---------------------------------------------------------------------------- #
from __future__ import annotations

from shared.base_callbacks import BaseAgentCallbacks
from strands.hooks import AfterToolCallEvent, BeforeToolCallEvent


class AgentCallbacks(BaseAgentCallbacks):
    """Class to handle callbacks for swarm agent operations.

    This class extends BaseAgentCallbacks for swarm agent operations including
    tool invocations and knowledge base retrievals. It manages metadata collection
    and logging during swarm execution.

    Attributes:
        _metadata (dict): Dictionary storing metadata generated by tools, e.g. Knowledge base references.
        _logger (Logger): Logger instance for recording agent operations and tool usage.
    """

    def log_tool_entries(self, event: BeforeToolCallEvent) -> None:
        """Logs information about tool invocation before it occurs.

        Args:
            event (BeforeToolCallEvent): Event containing metadata about the tool
                that will be invoked.

        Returns:
            None
        """
        specs = event.selected_tool.tool_spec if event.selected_tool else None

        self._nb_tool_invocations += 1

        self._logger.info(
            f"Agent is going to call tool #{self._nb_tool_invocations} in this turn",
            extra={"toolSpecifications": specs, "toolParameters": event.tool_use},
        )

        # Extract parameters using base class helper
        parameters = self._extract_tool_parameters(event, specs)

        # Publish tool invocation using base class helper
        tool_name = event.tool_use.get("name", "unknown")
        tool_description = specs.get("description", "") if specs else ""
        self._publish_tool_invocation(tool_name, tool_description, parameters)

    def log_tool_results(self, event: AfterToolCallEvent) -> None:
        """Logs tool results after tool execution.

        Args:
            event (AfterToolCallEvent): Event containing tool results.
        """
        if event.selected_tool:
            self._logger.info(
                "The tool returned a response",
                extra={
                    "payload": {
                        "toolName": event.selected_tool.tool_name,
                        "result": event.result,
                    }
                },
            )
